version: "3.9"

services:
  db:
    image: postgres
    container_name: rentx-db
    restart: always
#    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    environment:
      - POSTGRES_DB=rentx
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=brasil#123!
    networks:
      - net-rentx
    ports:
      - 5432:5432
  app:
    build: . #usa o Dockerfile que cria a imagem
    image: wsanada/rentx-app
    container_name: rentx-app
    volumes:
      - .:/usr/app
    networks:
      - net-rentx
    ports:
      - 3333:3333
      - 9229:9229
    # links:
    #   - db
    depends_on:
      - db

networks:
  net-rentx:
    name: net-rentx
    driver: bridge

volumes:
  pgdata:
    name: vol-rentx
    driver: local

#/* sobe os containers e libera o terminal */
#docker-compose up -d
#docker-compose stop
#docker-compose start

#/* mata os containers */
#docker-compose down ###mata os containers

#/* forca a recriação dos containers */
#docker-compose up --force-recreate -d
