version: "3.7"

services:
  db:
    image: postgres
    container_name: rentx-db
    restart: always
    tty: true
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_DB=rentx
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=brasil#123!
    networks:
      - rentx-net
    ports:
      - 5432:5432
  app:
    build: . #usa o Dockerfile que cria a imagem
    image: wsanada/rentx-app
    container_name: rentx-app
    volumes:
      - .:/usr/app
    networks:
      - rentx-net
    ports:
      - 3333:3333
      - 9229:9229
    depends_on:
      - db

networks:
  rentx-net:
    driver: bridge

volumes:
  pgdata:
    driver: local

#/* sobe os containers e libera o terminal */
#docker-compose up -d
#docker-compose stop
#docker-compose start

#/* mata os containers */
#docker-compose down ###mata os containers

#/* forca a recriação dos containers */
#docker-compose up --force-recreate -d
